#!/usr/bin/env bash
#
# Builds Crabsend for Arch Linux and packages it as a native pacman package.
#
#   scripts/build-arch.sh                  build, then package
#   scripts/build-arch.sh --install        build, package, then install with pacman
#   scripts/build-arch.sh --install-deps   install missing build dependencies first
#   scripts/build-arch.sh --no-build       package the release binary that is already built
#   scripts/build-arch.sh --clean          drop the staging directory before packaging
#
# The result is a `crabsend-bin-<version>-<rel>-<arch>.pkg.tar.zst` in
# `target/arch-pkg/`, installable with `sudo pacman -U <file>`.
set -euo pipefail

readonly app_name="crabsend"
readonly pkg_name="crabsend-bin"
readonly pkg_rel="1"

root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly root
readonly stage="$root/target/arch-pkg"

install_package=false
install_deps=false
do_build=true
do_clean=false

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die() { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# The leading comment block is the help text.
usage() {
    awk 'NR > 2 && /^#/ { sub(/^# ?/, ""); print; next } NR > 2 { exit }' "${BASH_SOURCE[0]}"
    exit 0
}

while (($#)); do
    case "$1" in
        -i | --install) install_package=true ;;
        --install-deps) install_deps=true ;;
        --no-build) do_build=false ;;
        --clean) do_clean=true ;;
        -h | --help) usage ;;
        *) die "unknown option: $1 (try --help)" ;;
    esac
    shift
done

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1${2:+ ($2)}"
}

# Tauri links these at run time; `pkg-config` module -> Arch package.
readonly -a dep_modules=(webkit2gtk-4.1 javascriptcoregtk-4.1 gtk+-3.0 ayatana-appindicator3-0.1 librsvg-2.0)
readonly -a dep_packages=(webkit2gtk-4.1 webkit2gtk-4.1 gtk3 libayatana-appindicator librsvg)

check_build_dependencies() {
    local missing=() i
    for i in "${!dep_modules[@]}"; do
        pkg-config --exists "${dep_modules[$i]}" || missing+=("${dep_packages[$i]}")
    done
    # Deduplicate while keeping order (webkit2gtk-4.1 appears twice).
    local unique=()
    for i in "${missing[@]:-}"; do
        [[ " ${unique[*]:-} " == *" $i "* ]] || unique+=("$i")
    done
    ((${#unique[@]} == 0)) && return 0

    log "missing build dependencies: ${unique[*]}"
    if $install_deps; then
        require_command sudo
        sudo pacman -S --needed --noconfirm "${unique[@]}"
        return 0
    fi
    die "install them first (or rerun with --install-deps):
    sudo pacman -S --needed ${unique[*]}"
}

build() {
    cd "$root"
    log "installing frontend dependencies"
    pnpm install --frozen-lockfile
    log "building the release binary"
    # beforeBuildCommand (vite) runs as part of this, so dist/ is refreshed.
    pnpm tauri build --no-bundle
    [[ -x "$root/target/release/crabsend-app" ]] ||
        die "expected the release binary at target/release/crabsend-app"
}

stage_files() {
    rm -rf "$stage"
    mkdir -p "$stage"
    install -m755 "$root/target/release/crabsend-app" "$stage/crabsend-app"
    install -m644 "$root/src-tauri/icons/32x32.png" "$stage/icon-32.png"
    install -m644 "$root/src-tauri/icons/64x64.png" "$stage/icon-64.png"
    install -m644 "$root/src-tauri/icons/128x128.png" "$stage/icon-128.png"
    install -m644 "$root/src-tauri/icons/128x128@2x.png" "$stage/icon-256.png"

    cat >"$stage/crabsend.desktop" <<'DESKTOP'
[Desktop Entry]
Type=Application
Name=Crabsend
GenericName=File Transfer
Comment=Transfer files to nearby devices on the local network
Exec=crabsend
Icon=crabsend
Terminal=false
Categories=Network;FileTransfer;Utility;
Keywords=localsend;localsend;transfer;share;lan;airdrop;
StartupNotify=true
StartupWMClass=Crabsend
DESKTOP
}

package() {
    local version arch
    version="$(node -p "require('$root/package.json').version")"
    case "$(uname -m)" in
        x86_64) arch=x86_64 ;;
        aarch64) arch=aarch64 ;;
        *) die "unsupported architecture: $(uname -m)" ;;
    esac

    log "packaging $pkg_name $version-$pkg_rel for $arch"
    # Checksums are computed over the staged payload, so a rebuild of the same
    # binary reproduces the same package metadata.
    local sums=() file
    for file in crabsend-app crabsend.desktop icon-32.png icon-64.png icon-128.png icon-256.png; do
        sums+=("$(sha256sum "$stage/$file" | cut -d' ' -f1)")
    done

    cat >"$stage/PKGBUILD" <<PKGBUILD
# Generated by scripts/build-arch.sh — the sources are the payload staged
# next to this file, so building only packages what was just compiled.
pkgname=$pkg_name
pkgver=$version
pkgrel=$pkg_rel
pkgdesc='LocalSend-compatible file transfer on the local network'
arch=('$arch')
url='https://github.com/moqsien/crabsend'
license=('MIT')
depends=('webkit2gtk-4.1' 'gtk3' 'libayatana-appindicator' 'librsvg')
provides=('$app_name')
conflicts=('$app_name')
source=('crabsend-app' 'crabsend.desktop' 'icon-32.png' 'icon-64.png' 'icon-128.png' 'icon-256.png')
sha256sums=(${sums[*]@Q})

package() {
    install -Dm755 "\$srcdir/crabsend-app" "\$pkgdir/usr/bin/$app_name"
    install -Dm644 "\$srcdir/crabsend.desktop" "\$pkgdir/usr/share/applications/$app_name.desktop"
    install -Dm644 "\$srcdir/icon-32.png" "\$pkgdir/usr/share/icons/hicolor/32x32/apps/$app_name.png"
    install -Dm644 "\$srcdir/icon-64.png" "\$pkgdir/usr/share/icons/hicolor/64x64/apps/$app_name.png"
    install -Dm644 "\$srcdir/icon-128.png" "\$pkgdir/usr/share/icons/hicolor/128x128/apps/$app_name.png"
    install -Dm644 "\$srcdir/icon-256.png" "\$pkgdir/usr/share/icons/hicolor/256x256/apps/$app_name.png"
}
PKGBUILD

    # makepkg refuses to run as root and needs its own scratch space.
    cd "$stage"
    makepkg --force --noconfirm

    local package
    package="$(find "$stage" -maxdepth 1 -name "$pkg_name-$version-$pkg_rel-*.pkg.tar.zst" -print -quit)"
    [[ -n "$package" ]] || die "makepkg did not produce a package"
    printf '%s\n' "$package" >"$stage/last-package"
}

report() {
    local package="$1"
    log "package: $package"
    pacman -Qip "$package" | sed -n '1,12p'
    log "contents"
    pacman -Qlp "$package" | sed 's/^/    /'
}

install_pkg() {
    local package="$1"
    cd "$root"
    log "installing with pacman (root required)"
    sudo pacman -U --noconfirm "$package"
    log "installed; run it with: $app_name"
}

require_command pnpm "install pnpm"
require_command cargo "install rust"
require_command node "install nodejs"
require_command makepkg "install base-devel"
require_command fakeroot "install base-devel"
require_command pkg-config "install pkgconf"

check_build_dependencies
$do_build && build

$do_clean && rm -rf "$stage"
stage_files
package

package_file="$(cat "$stage/last-package")"
report "$package_file"
if $install_package; then
    install_pkg "$package_file"
else
    log "install it with: sudo pacman -U $package_file"
    log "or rerun this script with --install"
fi
